# Find TargetDP
# TARGETDP_FOUND
# TARGETDP_INCLUDE_DIRS
# TARGETDP_LIBRARIES

find_path(TARGETDP_INCLUDE_DIRS
  NAMES targetDP.h
)
mark_as_advanced(TARGETDP_INCLUDE_DIRS)

find_library(TARGETDP_LIBRARIES
  NAMES target
)
mark_as_advanced(TARGETDP_LIBRARIES)

include( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( TargetDP REQUIRED_VARS TARGETDP_INCLUDE_DIRS TARGETDP_LIBRARIES)
